# Generated by Django 4.0.6 on 2025-04-01 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('location', models.CharField(default='India', max_length=255)),
                ('phone', models.IntegerField(null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('joined_date', models.DateField(null=True)),
                ('updated_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
