# Generated by Django 4.0.6 on 2025-04-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default=None, max_length=255, unique=True),
        ),
    ]
