# Generated by Django 4.1.4 on 2023-12-08 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(default='s.swarn619@gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='updated_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
